[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 8
y = 5

[keyboard]
bindings = [
   { key = "Return", mods = "Shift", action = "SpawnNewInstance" }
]
